# Hard-coded dataset of 100 named buildings with metro flag
buildings = {
  "La Beaubien Maison": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 992, '1 Bedroom': 1637, '2 Bedrooms': 2320},
    "amenities": ['Indoor Pool', 'Outdoor Pool', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 1.417, 'Concordia University': 2.329, 'Université de Montréal': 4.377, 'HEC Montréal': 5.951, 'Polytechnique Montréal': 5.999},
    "within_500m_metro": 'Yes',
  },
  "La Beaubien Pavilions": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 524, '1 Bedroom': 1222, '2 Bedrooms': 1540},
    "amenities": ['BBQ', 'Garden', 'Gym', 'Indoor Pool', 'Jacuzzi', 'Outdoor Pool', 'Patio', 'Social Room'],
    "appliances": ['A/C', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 7.171, 'Concordia University': 4.548, 'Université de Montréal': 0.787, 'HEC Montréal': 2.266, 'Polytechnique Montréal': 7.671},
    "within_500m_metro": 'Yes',
  },
  "La Beaubien-Est Parc 27": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'No',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1179, '1 Bedroom': 1803, '2 Bedrooms': 2631},
    "amenities": ['Gym', 'Indoor Pool', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 8.527, 'Concordia University': 7.64, 'Université de Montréal': 4.193, 'HEC Montréal': 2.601, 'Polytechnique Montréal': 7.383},
    "within_500m_metro": 'Yes',
  },
  "La Beaver Hall Place 66": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1032, '1 Bedroom': 1673, '2 Bedrooms': 2387},
    "amenities": ['BBQ', 'Gym', 'Indoor Pool', 'Library', 'Patio', 'Social Room'],
    "appliances": ['Heater', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 0.299, 'Concordia University': 7.807, 'Université de Montréal': 2.168, 'HEC Montréal': 0.128, 'Polytechnique Montréal': 9.131},
    "within_500m_metro": 'Yes',
  },
  "La Bishop Residences": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1350, '1 Bedroom': 1955, '2 Bedrooms': 2917},
    "amenities": ['Gym', 'Indoor Pool', 'Laundry Room', 'Outdoor Pool', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 5.84, 'Concordia University': 0.934, 'Université de Montréal': 1.77, 'HEC Montréal': 2.417, 'Polytechnique Montréal': 7.193},
    "within_500m_metro": 'Yes',
  },
  "La Bleury Pavilions 68": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['4+ Bedrooms', '2 Bedrooms', '3 Bedrooms'],
    "prices_monthly": {'2 Bedrooms': 2191, '3 Bedrooms': 2739, '4+ Bedrooms': 4287},
    "amenities": ['BBQ', 'Gym', 'Indoor Pool', 'Jacuzzi', 'Library', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 3.491, 'Concordia University': 2.773, 'Université de Montréal': 1.79, 'HEC Montréal': 4.692, 'Polytechnique Montréal': 4.386},
    "within_500m_metro": 'No',
  },
  "La Clark Commons": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 778, '1 Bedroom': 1447, '2 Bedrooms': 1964},
    "amenities": ['Garden', 'Gym', 'Indoor Pool', 'Jacuzzi', 'Laundry Room', 'Social Room'],
    "appliances": ['Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 5.381, 'Concordia University': 0.346, 'Université de Montréal': 6.404, 'HEC Montréal': 8.848, 'Polytechnique Montréal': 9.611},
    "within_500m_metro": 'Yes',
  },
  "La Clark Lofts": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 655, '1 Bedroom': 1337, '2 Bedrooms': 1758},
    "amenities": ['BBQ', 'Garden', 'Gym', 'Indoor Pool', 'Library', 'Sauna', 'Social Room'],
    "appliances": ['A/C', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 3.971, 'Concordia University': 9.889, 'Université de Montréal': 9.871, 'HEC Montréal': 0.51, 'Polytechnique Montréal': 7.715},
    "within_500m_metro": 'Yes',
  },
  "La Crescent Court 23": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['4+ Bedrooms', '3 Bedrooms'],
    "prices_monthly": {'3 Bedrooms': 2981, '4+ Bedrooms': 4577},
    "amenities": ['Gym', 'Indoor Pool', 'Sauna', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 0.809, 'Concordia University': 1.039, 'Université de Montréal': 0.644, 'HEC Montréal': 7.58, 'Polytechnique Montréal': 0.675},
    "within_500m_metro": 'Yes',
  },
  "La De Bullion Commons": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1334, '1 Bedroom': 1941, '2 Bedrooms': 2890},
    "amenities": ['BBQ', 'Garden', 'Gym', 'Indoor Pool', 'Jacuzzi', 'Laundry Room', 'Library', 'Social Room'],
    "appliances": ['A/C', 'Heater', 'In-unit Dryer', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 7.014, 'Concordia University': 4.738, 'Université de Montréal': 3.875, 'HEC Montréal': 2.655, 'Polytechnique Montréal': 4.212},
    "within_500m_metro": 'No',
  },
  "La De Bullion Gardens": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['2 Bedrooms', '3 Bedrooms'],
    "prices_monthly": {'2 Bedrooms': 3655, '3 Bedrooms': 4568},
    "amenities": ['Garden', 'Gym', 'Indoor Pool', 'Jacuzzi', 'Outdoor Pool', 'Sauna', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer'],
    "distance_to_campuses_km": {'McGill University': 7.755, 'Concordia University': 0.708, 'Université de Montréal': 0.493, 'HEC Montréal': 0.806, 'Polytechnique Montréal': 9.674},
    "within_500m_metro": 'Yes',
  },
  "La Drummond Manor 27": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1221, '1 Bedroom': 1841, '2 Bedrooms': 2702},
    "amenities": ['Garden', 'Gym', 'Indoor Pool', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 3.775, 'Concordia University': 1.211, 'Université de Montréal': 6.867, 'HEC Montréal': 3.763, 'Polytechnique Montréal': 0.199},
    "within_500m_metro": 'No',
  },
  "La Hutchison Court": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['3 Bedrooms'],
    "prices_monthly": {'3 Bedrooms': 2995},
    "amenities": ['BBQ', 'Gym', 'Indoor Pool', 'Laundry Room', 'Sauna', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 6.212, 'Concordia University': 9.385, 'Université de Montréal': 6.236, 'HEC Montréal': 4.087, 'Polytechnique Montréal': 7.726},
    "within_500m_metro": 'No',
  },
  "La Masson Lofts 10": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 649, '1 Bedroom': 1332, '2 Bedrooms': 1748},
    "amenities": ['Gym', 'Indoor Pool', 'Library', 'Outdoor Pool', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 0.871, 'Concordia University': 8.332, 'Université de Montréal': 0.56, 'HEC Montréal': 0.238, 'Polytechnique Montréal': 2.693},
    "within_500m_metro": 'No',
  },
  "La Peel Lofts": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1151, '1 Bedroom': 1779, '2 Bedrooms': 2585},
    "amenities": ['BBQ', 'Gym', 'Indoor Pool', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Dryer'],
    "distance_to_campuses_km": {'McGill University': 5.899, 'Concordia University': 5.426, 'Université de Montréal': 7.638, 'HEC Montréal': 0.821, 'Polytechnique Montréal': 0.198},
    "within_500m_metro": 'Yes',
  },
  "La Peel Residences 2": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['4+ Bedrooms'],
    "prices_monthly": {'4+ Bedrooms': 5521},
    "amenities": ['Gym', 'Indoor Pool', 'Outdoor Pool', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 8.648, 'Concordia University': 0.992, 'Université de Montréal': 4.198, 'HEC Montréal': 8.819, 'Polytechnique Montréal': 4.498},
    "within_500m_metro": 'Yes',
  },
  "La St-Laurent Lofts": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 725, '1 Bedroom': 1400, '2 Bedrooms': 1875},
    "amenities": ['Gym', 'Indoor Pool', 'Jacuzzi', 'Laundry Room', 'Sauna', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Dryer', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 9.553, 'Concordia University': 8.819, 'Université de Montréal': 8.672, 'HEC Montréal': 2.597, 'Polytechnique Montréal': 7.163},
    "within_500m_metro": 'No',
  },
  "La Viger Maison": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 749, '1 Bedroom': 1422, '2 Bedrooms': 1916},
    "amenities": ['Gym', 'Indoor Pool', 'Jacuzzi'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Dryer', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 8.299, 'Concordia University': 6.244, 'Université de Montréal': 3.882, 'HEC Montréal': 0.972, 'Polytechnique Montréal': 8.797},
    "within_500m_metro": 'No',
  },
  "La Édouard-Montpetit Terraces 87": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1288, '1 Bedroom': 1901, '2 Bedrooms': 2814},
    "amenities": ['BBQ', 'Gym', 'Indoor Pool', 'Library', 'Outdoor Pool', 'Patio', 'Sauna', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 0.957, 'Concordia University': 9.761, 'Université de Montréal': 5.531, 'HEC Montréal': 4.035, 'Polytechnique Montréal': 9.922},
    "within_500m_metro": 'No',
  },
  "La Édouard-Montpetit Tower": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['2 Bedrooms'],
    "prices_monthly": {'2 Bedrooms': 2110},
    "amenities": ['BBQ', 'Garden', 'Gym', 'Indoor Pool', 'Laundry Room', 'Patio', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 5.501, 'Concordia University': 0.398, 'Université de Montréal': 8.642, 'HEC Montréal': 1.938, 'Polytechnique Montréal': 5.279},
    "within_500m_metro": 'Yes',
  },
  "Le Atwater Flats": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 525, '1 Bedroom': 1222, '2 Bedrooms': 1541},
    "amenities": ['Gym', 'Indoor Pool', 'Jacuzzi', 'Laundry Room', 'Patio', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 7.974, 'Concordia University': 6.581, 'Université de Montréal': 0.661, 'HEC Montréal': 1.586, 'Polytechnique Montréal': 1.263},
    "within_500m_metro": 'No',
  },
  "Le Beaubien-Est Place": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 562, '1 Bedroom': 1255, '2 Bedrooms': 1603},
    "amenities": ['Gym', 'Indoor Pool', 'Outdoor Pool', 'Patio'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 3.599, 'Concordia University': 0.233, 'Université de Montréal': 0.531, 'HEC Montréal': 0.723, 'Polytechnique Montréal': 8.06},
    "within_500m_metro": 'Yes',
  },
  "Le Berri Maison": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 907, '1 Bedroom': 1562, '2 Bedrooms': 2179},
    "amenities": ['Gym', 'Indoor Pool', 'Patio'],
    "appliances": ['Heater', 'In-unit Dryer', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 4.823, 'Concordia University': 2.205, 'Université de Montréal': 0.612, 'HEC Montréal': 9.502, 'Polytechnique Montréal': 2.244},
    "within_500m_metro": 'Yes',
  },
  "Le Berri Square": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1092, '1 Bedroom': 1726, '2 Bedrooms': 2486},
    "amenities": ['Garden', 'Gym', 'Indoor Pool', 'Patio', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 5.922, 'Concordia University': 4.841, 'Université de Montréal': 1.29, 'HEC Montréal': 0.451, 'Polytechnique Montréal': 7.131},
    "within_500m_metro": 'No',
  },
  "Le Bleury Manor": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 816, '1 Bedroom': 1481, '2 Bedrooms': 2027},
    "amenities": ['BBQ', 'Garden', 'Gym', 'Indoor Pool', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 2.41, 'Concordia University': 3.941, 'Université de Montréal': 6.813, 'HEC Montréal': 3.797, 'Polytechnique Montréal': 1.773},
    "within_500m_metro": 'Yes',
  },
  "Le Bleury Vista 54": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1079, '1 Bedroom': 1714, '2 Bedrooms': 2464},
    "amenities": ['Gym', 'Indoor Pool', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 1.975, 'Concordia University': 0.883, 'Université de Montréal': 0.484, 'HEC Montréal': 4.121, 'Polytechnique Montréal': 0.862},
    "within_500m_metro": 'No',
  },
  "Le Crescent Residences": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 585, '1 Bedroom': 1276, '2 Bedrooms': 1642},
    "amenities": ['Gym', 'Indoor Pool', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 8.293, 'Concordia University': 0.85, 'Université de Montréal': 6.014, 'HEC Montréal': 1.709, 'Polytechnique Montréal': 5.981},
    "within_500m_metro": 'No',
  },
  "Le De Lorimier Vista": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['2 Bedrooms', '4+ Bedrooms', '3 Bedrooms'],
    "prices_monthly": {'2 Bedrooms': 3093, '3 Bedrooms': 3866, '4+ Bedrooms': 5639},
    "amenities": ['Gym', 'Jacuzzi', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 1.038, 'Concordia University': 3.405, 'Université de Montréal': 9.774, 'HEC Montréal': 5.231, 'Polytechnique Montréal': 6.462},
    "within_500m_metro": 'Yes',
  },
  "Le Gouin Lofts": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1187, '1 Bedroom': 1811, '2 Bedrooms': 2645},
    "amenities": ['Garden', 'Gym', 'Indoor Pool', 'Laundry Room', 'Outdoor Pool'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 0.812, 'Concordia University': 8.111, 'Université de Montréal': 6.803, 'HEC Montréal': 5.971, 'Polytechnique Montréal': 0.909},
    "within_500m_metro": 'Yes',
  },
  "Le Gouin Manor 33": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['4+ Bedrooms', '2 Bedrooms', '3 Bedrooms'],
    "prices_monthly": {'2 Bedrooms': 2014, '3 Bedrooms': 2517, '4+ Bedrooms': 4020},
    "amenities": ['Garden', 'Gym', 'Indoor Pool', 'Laundry Room', 'Sauna', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer'],
    "distance_to_campuses_km": {'McGill University': 0.411, 'Concordia University': 8.596, 'Université de Montréal': 1.144, 'HEC Montréal': 6.167, 'Polytechnique Montréal': 0.182},
    "within_500m_metro": 'No',
  },
  "Le Jean-Talon Commons 41": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 912, '1 Bedroom': 1567, '2 Bedrooms': 2187},
    "amenities": ['Gym', 'Indoor Pool', 'Library', 'Patio'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 3.823, 'Concordia University': 0.809, 'Université de Montréal': 3.165, 'HEC Montréal': 1.836, 'Polytechnique Montréal': 1.519},
    "within_500m_metro": 'Yes',
  },
  "Le Milton Flats 75": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['3 Bedrooms', '2 Bedrooms', '4+ Bedrooms'],
    "prices_monthly": {'2 Bedrooms': 2366, '3 Bedrooms': 2958, '4+ Bedrooms': 4549},
    "amenities": ['Garden', 'Gym', 'Indoor Pool', 'Laundry Room', 'Social Room'],
    "appliances": ['A/C', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 1.056, 'Concordia University': 4.902, 'Université de Montréal': 8.45, 'HEC Montréal': 3.385, 'Polytechnique Montréal': 1.455},
    "within_500m_metro": 'Yes',
  },
  "Le Milton Place": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1062, '1 Bedroom': 1699, '2 Bedrooms': 2436},
    "amenities": ['Gym', 'Laundry Room', 'Patio', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 3.691, 'Concordia University': 6.772, 'Université de Montréal': 3.587, 'HEC Montréal': 3.421, 'Polytechnique Montréal': 4.686},
    "within_500m_metro": 'Yes',
  },
  "Le Mont-Royal Court": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['3 Bedrooms', '4+ Bedrooms'],
    "prices_monthly": {'3 Bedrooms': 4040, '4+ Bedrooms': 5848},
    "amenities": ['Gym', 'Indoor Pool', 'Library', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 6.502, 'Concordia University': 1.077, 'Université de Montréal': 2.834, 'HEC Montréal': 0.206, 'Polytechnique Montréal': 1.834},
    "within_500m_metro": 'No',
  },
  "Le Mont-Royal Maison": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 875, '1 Bedroom': 1533, '2 Bedrooms': 2124},
    "amenities": ['Gym', 'Indoor Pool', 'Jacuzzi', 'Laundry Room', 'Library', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 2.902, 'Concordia University': 8.417, 'Université de Montréal': 8.514, 'HEC Montréal': 6.494, 'Polytechnique Montréal': 3.49},
    "within_500m_metro": 'Yes',
  },
  "Le Notre-Dame Flats": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1065, '1 Bedroom': 1702, '2 Bedrooms': 2442},
    "amenities": ['Indoor Pool', 'Jacuzzi', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 5.137, 'Concordia University': 6.013, 'Université de Montréal': 0.121, 'HEC Montréal': 9.389, 'Polytechnique Montréal': 0.713},
    "within_500m_metro": 'Yes',
  },
  "Le Outremont Lofts 78": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 728, '1 Bedroom': 1402, '2 Bedrooms': 1879},
    "amenities": ['BBQ', 'Gym', 'Indoor Pool', 'Patio', 'Social Room'],
    "appliances": ['A/C', 'Heater', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 6.14, 'Concordia University': 9.999, 'Université de Montréal': 0.917, 'HEC Montréal': 0.692, 'Polytechnique Montréal': 0.186},
    "within_500m_metro": 'Yes',
  },
  "Le St-Catherine Tower 30": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1140, '1 Bedroom': 1769, '2 Bedrooms': 2567},
    "amenities": ['Gym', 'Indoor Pool', 'Jacuzzi', 'Laundry Room', 'Library', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 8.437, 'Concordia University': 3.7, 'Université de Montréal': 5.665, 'HEC Montréal': 6.246, 'Polytechnique Montréal': 0.377},
    "within_500m_metro": 'Yes',
  },
  "Le St-Hubert Parc": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['4+ Bedrooms'],
    "prices_monthly": {'4+ Bedrooms': 6658},
    "amenities": ['Gym', 'Indoor Pool', 'Laundry Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer'],
    "distance_to_campuses_km": {'McGill University': 4.21, 'Concordia University': 0.469, 'Université de Montréal': 4.924, 'HEC Montréal': 7.909, 'Polytechnique Montréal': 1.642},
    "within_500m_metro": 'Yes',
  },
  "Le St-Laurent Square 47": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['3 Bedrooms', '2 Bedrooms', '4+ Bedrooms'],
    "prices_monthly": {'2 Bedrooms': 2229, '3 Bedrooms': 2786, '4+ Bedrooms': 4344},
    "amenities": ['Gym', 'Indoor Pool', 'Laundry Room', 'Outdoor Pool'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 8.439, 'Concordia University': 7.118, 'Université de Montréal': 6.665, 'HEC Montréal': 6.812, 'Polytechnique Montréal': 6.278},
    "within_500m_metro": 'No',
  },
  "Les Beaubien Court 28": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1391, '1 Bedroom': 1992, '2 Bedrooms': 2985},
    "amenities": ['Indoor Pool', 'Patio', 'Sauna'],
    "appliances": ['A/C', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 7.526, 'Concordia University': 0.637, 'Université de Montréal': 4.567, 'HEC Montréal': 1.62, 'Polytechnique Montréal': 1.358},
    "within_500m_metro": 'No',
  },
  "Les Beaubien-Est Square 93": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 831, '1 Bedroom': 1494, '2 Bedrooms': 2052},
    "amenities": ['Gym', 'Indoor Pool', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 8.728, 'Concordia University': 1.362, 'Université de Montréal': 2.149, 'HEC Montréal': 1.108, 'Polytechnique Montréal': 0.943},
    "within_500m_metro": 'Yes',
  },
  "Les Beaver Hall Lofts": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['4+ Bedrooms', '3 Bedrooms', '2 Bedrooms'],
    "prices_monthly": {'2 Bedrooms': 3699, '3 Bedrooms': 4624, '4+ Bedrooms': 6549},
    "amenities": ['BBQ', 'Gym', 'Indoor Pool', 'Jacuzzi', 'Library', 'Outdoor Pool', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 4.558, 'Concordia University': 7.954, 'Université de Montréal': 3.552, 'HEC Montréal': 1.942, 'Polytechnique Montréal': 6.36},
    "within_500m_metro": 'Yes',
  },
  "Les Beaver Hall Maison 34": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['4+ Bedrooms'],
    "prices_monthly": {'4+ Bedrooms': 5527},
    "amenities": ['BBQ', 'Indoor Pool', 'Jacuzzi', 'Laundry Room', 'Library', 'Outdoor Pool', 'Sauna'],
    "appliances": ['Heater', 'In-unit Dryer', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 3.418, 'Concordia University': 2.902, 'Université de Montréal': 0.133, 'HEC Montréal': 6.248, 'Polytechnique Montréal': 1.948},
    "within_500m_metro": 'No',
  },
  "Les Bishop Commons": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 675, '1 Bedroom': 1356, '2 Bedrooms': 1792},
    "amenities": ['Gym', 'Indoor Pool', 'Jacuzzi', 'Library', 'Patio', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 5.052, 'Concordia University': 8.693, 'Université de Montréal': 1.581, 'HEC Montréal': 9.002, 'Polytechnique Montréal': 5.934},
    "within_500m_metro": 'Yes',
  },
  "Les Bleury Court": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1330, '1 Bedroom': 1938, '2 Bedrooms': 2883},
    "amenities": ['Garden', 'Gym', 'Indoor Pool', 'Jacuzzi', 'Library', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 6.639, 'Concordia University': 8.135, 'Université de Montréal': 5.186, 'HEC Montréal': 4.178, 'Polytechnique Montréal': 6.06},
    "within_500m_metro": 'No',
  },
  "Les Clark Square": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 838, '1 Bedroom': 1500, '2 Bedrooms': 2063},
    "amenities": ['BBQ', 'Garden', 'Gym', 'Indoor Pool', 'Laundry Room', 'Outdoor Pool', 'Patio', 'Social Room'],
    "appliances": ['A/C', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 1.935, 'Concordia University': 2.132, 'Université de Montréal': 2.676, 'HEC Montréal': 7.227, 'Polytechnique Montréal': 7.848},
    "within_500m_metro": 'Yes',
  },
  "Les Crescent Maison": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 536, '1 Bedroom': 1232, '2 Bedrooms': 1560},
    "amenities": ['BBQ', 'Garden', 'Gym', 'Indoor Pool', 'Jacuzzi', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 7.032, 'Concordia University': 0.276, 'Université de Montréal': 0.204, 'HEC Montréal': 8.312, 'Polytechnique Montréal': 4.422},
    "within_500m_metro": 'Yes',
  },
  "Les De Bullion Terraces": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['3 Bedrooms'],
    "prices_monthly": {'3 Bedrooms': 3252},
    "amenities": ['Gym', 'Indoor Pool', 'Jacuzzi', 'Laundry Room', 'Social Room'],
    "appliances": ['Heater', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 3.183, 'Concordia University': 7.74, 'Université de Montréal': 4.538, 'HEC Montréal': 8.076, 'Polytechnique Montréal': 8.466},
    "within_500m_metro": 'No',
  },
  "Les De La Montagne Square": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1249, '1 Bedroom': 1866, '2 Bedrooms': 2748},
    "amenities": ['Gym', 'Indoor Pool', 'Jacuzzi', 'Library', 'Outdoor Pool', 'Patio', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 0.245, 'Concordia University': 0.178, 'Université de Montréal': 3.854, 'HEC Montréal': 2.628, 'Polytechnique Montréal': 7.909},
    "within_500m_metro": 'Yes',
  },
  "Les De Lorimier Flats": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['4+ Bedrooms', '2 Bedrooms', '3 Bedrooms'],
    "prices_monthly": {'2 Bedrooms': 2059, '3 Bedrooms': 2574, '4+ Bedrooms': 4089},
    "amenities": ['Garden', 'Indoor Pool', 'Outdoor Pool', 'Patio', 'Social Room'],
    "appliances": ['A/C', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 0.163, 'Concordia University': 3.542, 'Université de Montréal': 7.177, 'HEC Montréal': 1.015, 'Polytechnique Montréal': 5.297},
    "within_500m_metro": 'Yes',
  },
  "Les Drummond Residences": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1122, '1 Bedroom': 1753, '2 Bedrooms': 2536},
    "amenities": ['BBQ', 'Garden', 'Gym', 'Indoor Pool', 'Jacuzzi', 'Library', 'Outdoor Pool', 'Patio', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 4.135, 'Concordia University': 8.475, 'Université de Montréal': 5.315, 'HEC Montréal': 0.772, 'Polytechnique Montréal': 2.314},
    "within_500m_metro": 'No',
  },
  "Les Hutchison Manor 13": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['2 Bedrooms'],
    "prices_monthly": {'2 Bedrooms': 2357},
    "amenities": ['BBQ', 'Garden', 'Gym', 'Indoor Pool', 'Laundry Room', 'Sauna', 'Social Room'],
    "appliances": ['A/C', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 3.157, 'Concordia University': 6.187, 'Université de Montréal': 5.813, 'HEC Montréal': 0.565, 'Polytechnique Montréal': 6.489},
    "within_500m_metro": 'Yes',
  },
  "Les Hutchison Parc": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 917, '1 Bedroom': 1571, '2 Bedrooms': 2195},
    "amenities": ['Indoor Pool', 'Outdoor Pool', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 7.788, 'Concordia University': 6.431, 'Université de Montréal': 0.433, 'HEC Montréal': 0.485, 'Polytechnique Montréal': 4.561},
    "within_500m_metro": 'Yes',
  },
  "Les Jeanne-Mance Place": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['2 Bedrooms', '3 Bedrooms'],
    "prices_monthly": {'2 Bedrooms': 3358, '3 Bedrooms': 4198},
    "amenities": ['Gym', 'Indoor Pool', 'Library', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 3.509, 'Concordia University': 7.976, 'Université de Montréal': 5.752, 'HEC Montréal': 3.275, 'Polytechnique Montréal': 6.294},
    "within_500m_metro": 'No',
  },
  "Les Milton Residences": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['4+ Bedrooms', '3 Bedrooms'],
    "prices_monthly": {'3 Bedrooms': 3475, '4+ Bedrooms': 5170},
    "amenities": ['BBQ', 'Garden', 'Gym', 'Indoor Pool', 'Jacuzzi', 'Laundry Room', 'Patio', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer'],
    "distance_to_campuses_km": {'McGill University': 0.91, 'Concordia University': 1.385, 'Université de Montréal': 4.223, 'HEC Montréal': 6.283, 'Polytechnique Montréal': 2.284},
    "within_500m_metro": 'Yes',
  },
  "Les Mont-Royal Square 9": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 906, '1 Bedroom': 1561, '2 Bedrooms': 2177},
    "amenities": ['BBQ', 'Gym', 'Indoor Pool', 'Jacuzzi', 'Patio', 'Sauna', 'Social Room'],
    "appliances": ['A/C', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 3.19, 'Concordia University': 9.101, 'Université de Montréal': 2.609, 'HEC Montréal': 6.131, 'Polytechnique Montréal': 2.36},
    "within_500m_metro": 'Yes',
  },
  "Les Notre-Dame Parc 72": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1363, '1 Bedroom': 1968, '2 Bedrooms': 2939},
    "amenities": ['BBQ', 'Gym', 'Indoor Pool', 'Outdoor Pool', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 1.216, 'Concordia University': 3.989, 'Université de Montréal': 0.491, 'HEC Montréal': 1.575, 'Polytechnique Montréal': 9.35},
    "within_500m_metro": 'Yes',
  },
  "Les Peel Gardens": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['2 Bedrooms', '3 Bedrooms'],
    "prices_monthly": {'2 Bedrooms': 3501, '3 Bedrooms': 4377},
    "amenities": ['BBQ', 'Garden', 'Gym', 'Indoor Pool', 'Laundry Room', 'Library'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 7.774, 'Concordia University': 8.303, 'Université de Montréal': 5.563, 'HEC Montréal': 5.832, 'Polytechnique Montréal': 7.945},
    "within_500m_metro": 'Yes',
  },
  "Les Peel Residences 38": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['2 Bedrooms'],
    "prices_monthly": {'2 Bedrooms': 3855},
    "amenities": ['Garden', 'Gym', 'Indoor Pool', 'Jacuzzi', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 4.477, 'Concordia University': 3.507, 'Université de Montréal': 2.81, 'HEC Montréal': 7.809, 'Polytechnique Montréal': 8.826},
    "within_500m_metro": 'No',
  },
  "Les St-Catherine Court": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['3 Bedrooms', '2 Bedrooms'],
    "prices_monthly": {'2 Bedrooms': 2480, '3 Bedrooms': 3100},
    "amenities": ['Gym', 'Indoor Pool', 'Jacuzzi', 'Laundry Room', 'Patio', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 4.399, 'Concordia University': 0.688, 'Université de Montréal': 3.03, 'HEC Montréal': 8.774, 'Polytechnique Montréal': 0.58},
    "within_500m_metro": 'Yes',
  },
  "Les St-Denis Vista 69": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 711, '1 Bedroom': 1388, '2 Bedrooms': 1852},
    "amenities": ['Gym', 'Outdoor Pool', 'Social Room'],
    "appliances": ['A/C', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 1.749, 'Concordia University': 8.475, 'Université de Montréal': 4.255, 'HEC Montréal': 6.993, 'Polytechnique Montréal': 3.126},
    "within_500m_metro": 'Yes',
  },
  "Les St-Hubert Parc": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 987, '1 Bedroom': 1632, '2 Bedrooms': 2311},
    "amenities": ['BBQ', 'Gym', 'Indoor Pool', 'Laundry Room', 'Outdoor Pool', 'Social Room'],
    "appliances": ['Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 6.25, 'Concordia University': 3.136, 'Université de Montréal': 6.966, 'HEC Montréal': 0.26, 'Polytechnique Montréal': 5.678},
    "within_500m_metro": 'Yes',
  },
  "Les St-Laurent Tower 26": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 963, '1 Bedroom': 1611, '2 Bedrooms': 2271},
    "amenities": ['BBQ', 'Indoor Pool', 'Jacuzzi', 'Laundry Room', 'Outdoor Pool', 'Sauna', 'Social Room'],
    "appliances": ['Heater', 'In-unit Dryer', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 0.885, 'Concordia University': 0.941, 'Université de Montréal': 5.605, 'HEC Montréal': 2.847, 'Polytechnique Montréal': 8.941},
    "within_500m_metro": 'Yes',
  },
  "Les Van Horne Court": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 692, '1 Bedroom': 1370, '2 Bedrooms': 1820},
    "amenities": ['Gym', 'Library', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 0.159, 'Concordia University': 1.195, 'Université de Montréal': 6.367, 'HEC Montréal': 0.394, 'Polytechnique Montréal': 0.737},
    "within_500m_metro": 'No',
  },
  "Les Viger Court": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 712, '1 Bedroom': 1388, '2 Bedrooms': 1853},
    "amenities": ['BBQ', 'Indoor Pool', 'Jacuzzi', 'Laundry Room', 'Sauna', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 2.042, 'Concordia University': 3.277, 'Université de Montréal': 7.899, 'HEC Montréal': 1.623, 'Polytechnique Montréal': 8.703},
    "within_500m_metro": 'Yes',
  },
  "Les Viger Gardens 39": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 811, '1 Bedroom': 1476, '2 Bedrooms': 2018},
    "amenities": ['Garden', 'Gym', 'Indoor Pool', 'Jacuzzi', 'Sauna', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 0.895, 'Concordia University': 1.428, 'Université de Montréal': 0.534, 'HEC Montréal': 8.834, 'Polytechnique Montréal': 0.359},
    "within_500m_metro": 'No',
  },
  "Les Viger Maison": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1160, '1 Bedroom': 1786, '2 Bedrooms': 2599},
    "amenities": ['Gym', 'Laundry Room', 'Library', 'Patio', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 2.749, 'Concordia University': 1.503, 'Université de Montréal': 5.512, 'HEC Montréal': 4.176, 'Polytechnique Montréal': 7.633},
    "within_500m_metro": 'Yes',
  },
  "Les Villeray Residences": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 874, '1 Bedroom': 1532, '2 Bedrooms': 2123},
    "amenities": ['BBQ', 'Garden', 'Gym', 'Indoor Pool', 'Patio'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 1.06, 'Concordia University': 5.382, 'Université de Montréal': 9.338, 'HEC Montréal': 0.471, 'Polytechnique Montréal': 3.325},
    "within_500m_metro": 'Yes',
  },
  "Les Édouard-Montpetit Manor": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 687, '1 Bedroom': 1366, '2 Bedrooms': 1811},
    "amenities": ['BBQ', 'Indoor Pool', 'Jacuzzi', 'Library', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 5.161, 'Concordia University': 6.789, 'Université de Montréal': 0.459, 'HEC Montréal': 3.071, 'Polytechnique Montréal': 9.951},
    "within_500m_metro": 'Yes',
  },
  "The Atwater Gardens": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1248, '1 Bedroom': 1865, '2 Bedrooms': 2747},
    "amenities": ['Gym', 'Indoor Pool', 'Library', 'Patio', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 2.599, 'Concordia University': 1.289, 'Université de Montréal': 9.027, 'HEC Montréal': 6.062, 'Polytechnique Montréal': 0.53},
    "within_500m_metro": 'No',
  },
  "The Beaubien Lofts": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1395, '1 Bedroom': 1995, '2 Bedrooms': 2991},
    "amenities": ['Gym', 'Indoor Pool', 'Jacuzzi', 'Laundry Room', 'Library', 'Sauna'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 0.389, 'Concordia University': 0.154, 'Université de Montréal': 1.297, 'HEC Montréal': 4.731, 'Polytechnique Montréal': 4.472},
    "within_500m_metro": 'Yes',
  },
  "The Beaver Hall Tower 37": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['4+ Bedrooms'],
    "prices_monthly": {'4+ Bedrooms': 4562},
    "amenities": ['Gym', 'Indoor Pool', 'Library', 'Outdoor Pool', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 5.757, 'Concordia University': 6.45, 'Université de Montréal': 2.045, 'HEC Montréal': 3.416, 'Polytechnique Montréal': 0.565},
    "within_500m_metro": 'Yes',
  },
  "The Berri Place 98": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['3 Bedrooms'],
    "prices_monthly": {'3 Bedrooms': 3135},
    "amenities": ['Garden', 'Gym', 'Jacuzzi', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 5.562, 'Concordia University': 0.508, 'Université de Montréal': 9.457, 'HEC Montréal': 6.75, 'Polytechnique Montréal': 4.508},
    "within_500m_metro": 'Yes',
  },
  "The Bleury Lofts 2": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 934, '1 Bedroom': 1586, '2 Bedrooms': 2223},
    "amenities": ['BBQ', 'Gym', 'Indoor Pool', 'Sauna', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 0.784, 'Concordia University': 9.267, 'Université de Montréal': 6.764, 'HEC Montréal': 2.352, 'Polytechnique Montréal': 3.989},
    "within_500m_metro": 'No',
  },
  "The Clark Lofts 59": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 869, '1 Bedroom': 1528, '2 Bedrooms': 2115},
    "amenities": ['Garden', 'Indoor Pool', 'Outdoor Pool', 'Patio', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 0.126, 'Concordia University': 7.066, 'Université de Montréal': 2.11, 'HEC Montréal': 7.069, 'Polytechnique Montréal': 1.537},
    "within_500m_metro": 'Yes',
  },
  "The Clark Terraces": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 721, '1 Bedroom': 1396, '2 Bedrooms': 1868},
    "amenities": ['Gym', 'Indoor Pool', 'Library', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 0.391, 'Concordia University': 7.86, 'Université de Montréal': 7.564, 'HEC Montréal': 7.452, 'Polytechnique Montréal': 9.142},
    "within_500m_metro": 'Yes',
  },
  "The Crescent Lofts": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'No',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1164, '1 Bedroom': 1790, '2 Bedrooms': 2606},
    "amenities": ['Garden', 'Gym', 'Indoor Pool', 'Jacuzzi', 'Library', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 5.127, 'Concordia University': 9.081, 'Université de Montréal': 8.663, 'HEC Montréal': 5.548, 'Polytechnique Montréal': 8.493},
    "within_500m_metro": 'No',
  },
  "The Crescent Terraces 51": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1194, '1 Bedroom': 1817, '2 Bedrooms': 2657},
    "amenities": ['BBQ', 'Gym', 'Indoor Pool', 'Laundry Room', 'Library', 'Outdoor Pool', 'Sauna'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 1.295, 'Concordia University': 3.602, 'Université de Montréal': 2.875, 'HEC Montréal': 1.543, 'Polytechnique Montréal': 2.534},
    "within_500m_metro": 'Yes',
  },
  "The Drummond Pavilions": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1369, '1 Bedroom': 1972, '2 Bedrooms': 2948},
    "amenities": ['Gym', 'Indoor Pool', 'Laundry Room', 'Library', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer'],
    "distance_to_campuses_km": {'McGill University': 7.291, 'Concordia University': 2.326, 'Université de Montréal': 9.798, 'HEC Montréal': 1.846, 'Polytechnique Montréal': 1.289},
    "within_500m_metro": 'Yes',
  },
  "The Hutchison Tower 82": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1281, '1 Bedroom': 1894, '2 Bedrooms': 2801},
    "amenities": ['Gym', 'Jacuzzi', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 6.91, 'Concordia University': 0.842, 'Université de Montréal': 0.484, 'HEC Montréal': 2.074, 'Polytechnique Montréal': 4.828},
    "within_500m_metro": 'No',
  },
  "The Jean-Talon Commons": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1196, '1 Bedroom': 1819, '2 Bedrooms': 2660},
    "amenities": ['Gym', 'Indoor Pool', 'Outdoor Pool', 'Patio', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 0.351, 'Concordia University': 5.2, 'Université de Montréal': 3.767, 'HEC Montréal': 4.122, 'Polytechnique Montréal': 1.94},
    "within_500m_metro": 'Yes',
  },
  "The Jean-Talon Gardens": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1297, '1 Bedroom': 1908, '2 Bedrooms': 2828},
    "amenities": ['Garden', 'Gym', 'Indoor Pool', 'Library', 'Social Room'],
    "appliances": ['Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 6.642, 'Concordia University': 1.331, 'Université de Montréal': 3.602, 'HEC Montréal': 9.0, 'Polytechnique Montréal': 1.575},
    "within_500m_metro": 'Yes',
  },
  "The Jean-Talon Pavilions": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['3 Bedrooms'],
    "prices_monthly": {'3 Bedrooms': 4103},
    "amenities": ['Garden', 'Gym', 'Indoor Pool', 'Patio', 'Sauna', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 8.433, 'Concordia University': 4.227, 'Université de Montréal': 6.816, 'HEC Montréal': 2.423, 'Polytechnique Montréal': 3.573},
    "within_500m_metro": 'Yes',
  },
  "The Jeanne-Mance Flats": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['3 Bedrooms'],
    "prices_monthly": {'3 Bedrooms': 4773},
    "amenities": ['Indoor Pool', 'Laundry Room', 'Library', 'Patio', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 0.134, 'Concordia University': 0.132, 'Université de Montréal': 2.402, 'HEC Montréal': 1.067, 'Polytechnique Montréal': 3.205},
    "within_500m_metro": 'No',
  },
  "The Laurier Tower": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1006, '1 Bedroom': 1650, '2 Bedrooms': 2344},
    "amenities": ['Gym', 'Indoor Pool', 'Patio', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 2.848, 'Concordia University': 8.467, 'Université de Montréal': 9.059, 'HEC Montréal': 6.367, 'Polytechnique Montréal': 9.162},
    "within_500m_metro": 'No',
  },
  "The Masson Lofts 68": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 863, '1 Bedroom': 1522, '2 Bedrooms': 2105},
    "amenities": ['Gym', 'Indoor Pool', 'Library', 'Outdoor Pool', 'Social Room'],
    "appliances": ['A/C', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 6.568, 'Concordia University': 2.999, 'Université de Montréal': 6.893, 'HEC Montréal': 4.409, 'Polytechnique Montréal': 8.099},
    "within_500m_metro": 'No',
  },
  "The Masson Maison": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'No',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 606, '1 Bedroom': 1295, '2 Bedrooms': 1677},
    "amenities": ['BBQ', 'Garden', 'Gym', 'Library', 'Social Room'],
    "appliances": ['A/C', 'Heater', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 2.506, 'Concordia University': 2.188, 'Université de Montréal': 2.575, 'HEC Montréal': 0.873, 'Polytechnique Montréal': 0.63},
    "within_500m_metro": 'Yes',
  },
  "The Masson Pavilions": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 912, '1 Bedroom': 1566, '2 Bedrooms': 2187},
    "amenities": ['Gym', 'Indoor Pool', 'Jacuzzi', 'Laundry Room', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 6.935, 'Concordia University': 2.269, 'Université de Montréal': 0.692, 'HEC Montréal': 3.989, 'Polytechnique Montréal': 0.937},
    "within_500m_metro": 'No',
  },
  "The Mont-Royal Residences": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 786, '1 Bedroom': 1455, '2 Bedrooms': 1977},
    "amenities": ['Gym', 'Indoor Pool', 'Laundry Room', 'Patio', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 5.794, 'Concordia University': 8.775, 'Université de Montréal': 6.925, 'HEC Montréal': 7.18, 'Polytechnique Montréal': 4.613},
    "within_500m_metro": 'No',
  },
  "The Notre-Dame Court": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1214, '1 Bedroom': 1834, '2 Bedrooms': 2689},
    "amenities": ['BBQ', 'Gym', 'Indoor Pool', 'Laundry Room', 'Library', 'Outdoor Pool', 'Patio', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 1.345, 'Concordia University': 1.461, 'Université de Montréal': 4.65, 'HEC Montréal': 2.638, 'Polytechnique Montréal': 9.081},
    "within_500m_metro": 'Yes',
  },
  "The Outremont Manor": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['2 Bedrooms', '4+ Bedrooms', '3 Bedrooms'],
    "prices_monthly": {'2 Bedrooms': 3478, '3 Bedrooms': 4348, '4+ Bedrooms': 6217},
    "amenities": ['Gym', 'Indoor Pool', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 8.005, 'Concordia University': 2.74, 'Université de Montréal': 3.481, 'HEC Montréal': 6.278, 'Polytechnique Montréal': 1.068},
    "within_500m_metro": 'No',
  },
  "The Outremont Place": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['2 Bedrooms', '3 Bedrooms'],
    "prices_monthly": {'2 Bedrooms': 2657, '3 Bedrooms': 3322},
    "amenities": ['Gym', 'Indoor Pool', 'Sauna', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 0.639, 'Concordia University': 6.644, 'Université de Montréal': 7.704, 'HEC Montréal': 3.039, 'Polytechnique Montréal': 9.224},
    "within_500m_metro": 'Yes',
  },
  "The Peel Manor": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1214, '1 Bedroom': 1835, '2 Bedrooms': 2690},
    "amenities": ['BBQ', 'Gym', 'Library', 'Outdoor Pool', 'Social Room'],
    "appliances": ['A/C', 'Heater', 'In-unit Dryer'],
    "distance_to_campuses_km": {'McGill University': 4.413, 'Concordia University': 7.937, 'Université de Montréal': 9.7, 'HEC Montréal': 0.115, 'Polytechnique Montréal': 3.554},
    "within_500m_metro": 'No',
  },
  "The St-Catherine Tower": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['4+ Bedrooms', '2 Bedrooms'],
    "prices_monthly": {'2 Bedrooms': 3723, '4+ Bedrooms': 6584},
    "amenities": ['Gym', 'Indoor Pool', 'Jacuzzi', 'Laundry Room', 'Library', 'Outdoor Pool', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 4.854, 'Concordia University': 8.802, 'Université de Montréal': 4.061, 'HEC Montréal': 0.681, 'Polytechnique Montréal': 4.066},
    "within_500m_metro": 'Yes',
  },
  "The St-Hubert Parc": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1325, '1 Bedroom': 1933, '2 Bedrooms': 2875},
    "amenities": ['Gym', 'Indoor Pool', 'Patio', 'Social Room'],
    "appliances": ['Dishwasher', 'Heater', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 3.863, 'Concordia University': 2.697, 'Université de Montréal': 3.201, 'HEC Montréal': 3.667, 'Polytechnique Montréal': 0.777},
    "within_500m_metro": 'No',
  },
  "The St-Laurent Gardens 79": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 517, '1 Bedroom': 1215, '2 Bedrooms': 1528},
    "amenities": ['Gym', 'Indoor Pool', 'Patio'],
    "appliances": ['A/C', 'Heater', 'In-unit Dryer', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 2.387, 'Concordia University': 9.461, 'Université de Montréal': 0.888, 'HEC Montréal': 8.298, 'Polytechnique Montréal': 7.189},
    "within_500m_metro": 'No',
  },
  "The Viger Gardens": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 1381, '1 Bedroom': 1983, '2 Bedrooms': 2969},
    "amenities": ['Garden', 'Gym', 'Indoor Pool', 'Jacuzzi', 'Outdoor Pool', 'Patio', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 4.83, 'Concordia University': 7.211, 'Université de Montréal': 2.539, 'HEC Montréal': 3.365, 'Polytechnique Montréal': 0.478},
    "within_500m_metro": 'Yes',
  },
  "The Viger Pavilions": {
    "accommodation": 'Townhouse',
    "over_ten_floors": 'Not Applicable',
    "unit_types": ['4+ Bedrooms', '2 Bedrooms'],
    "prices_monthly": {'2 Bedrooms': 2073, '4+ Bedrooms': 4109},
    "amenities": ['BBQ', 'Gym', 'Indoor Pool', 'Outdoor Pool', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine', 'Microwave'],
    "distance_to_campuses_km": {'McGill University': 0.783, 'Concordia University': 5.67, 'Université de Montréal': 1.597, 'HEC Montréal': 8.982, 'Polytechnique Montréal': 0.193},
    "within_500m_metro": 'Yes',
  },
  "The Villeray Parc": {
    "accommodation": 'Condo/Apartment',
    "over_ten_floors": 'Yes',
    "unit_types": ['Studio', '1 Bedroom', '2 Bedrooms'],
    "prices_monthly": {'Studio': 660, '1 Bedroom': 1342, '2 Bedrooms': 1767},
    "amenities": ['BBQ', 'Laundry Room', 'Outdoor Pool', 'Sauna', 'Social Room'],
    "appliances": ['A/C', 'Dishwasher', 'Heater', 'In-unit Dryer', 'In-unit Washing Machine'],
    "distance_to_campuses_km": {'McGill University': 9.601, 'Concordia University': 0.979, 'Université de Montréal': 0.465, 'HEC Montréal': 0.907, 'Polytechnique Montréal': 5.212},
    "within_500m_metro": 'Yes',
  },
}